vich_uploader:
    db_driver: orm

    mappings:
       users:
           uri_prefix: /visuals/users
           upload_destination: '%kernel.project_dir%/public/visuals/users'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
